### ISSUE TITLE
城市id

### ISSUE THREAD

**Issue by Aiso0** [Mashiro2000/volunteer#2]
这个城市id 是用什么对照的

**Comment by Mashiro2000** [comment]
这个得自己抓包，

**Comment by Mashiro2000** [comment]
不加城市id也是1可以正常运行的

**Comment by Mashiro2000** [comment]
其实这个志愿汇抓取登录包，参数不变，直接post请求也可以正常登录
发布这个项目的主要原因是我第一次成功反编译😀

**Comment by GOIV1999** [comment]
> 其实这个志愿汇抓取登录包，参数不变，直接post请求也可以正常登录 发布这个项目的主要原因是我第一次成功反编译😀

充能失败
![WC1BXHEOI0LH0T6QRNNS_4](https://user-images.githubusercontent.com/59191936/141619080-12504ebc-db39-418d-bff5-1458045e277e.png)

**Comment by Aiso0** [comment]
> 
> 
> > 其实这个志愿汇抓取登录包，参数不变，直接post请求也可以正常登录 发布这个项目的主要原因是我第一次成功反编译 😀
> 
> 充能失败 ![WC1BXHEOI0LH0T6QRNNS_4](https://user-images.githubusercontent.com/59191936/141619080-12504ebc-db39-418d-bff5-1458045e277e.png)

这个应该跟城市id没关系，正如作者所说，我就算不设置城市id都可以

**Comment by Mashiro2000** [comment]
> > 其实这个志愿汇抓取登录包，参数不变，直接post请求也可以正常登录 发布这个项目的主要原因是我第一次成功反编译😀
> 
> 充能失败 ![WC1BXHEOI0LH0T6QRNNS_4](https://user-images.githubusercontent.com/59191936/141619080-12504ebc-db39-418d-bff5-1458045e277e.png)

请先提前绑定自己的学校
